server:
  port: 8085
spring:
  profiles:
    active: yubo
#man:
#  high: 178cm
#  height: 140kg
#  longs: 18cm
#  family: {father: 于圣旺,mother: 孙爱珍}
#  friend:
#    - cz
#    - zwy
#    - cjm
#  wife:
#    high: 158cm
#    height: 160kg

